apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeanalysis
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kubeanalysis
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: LOG_LEVEL
              value: "debug"
