apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeanalysis
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: kubeanalysis
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
