apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeanalysis-staging

namePrefix: staging-

commonLabels:
  app.kubernetes.io/environment: staging

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml

images:
  - name: kubeanalysis/kubeanalysis
    newTag: staging
